version: "3.9"
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    image: registry.cn-beijing.aliyuncs.com/yoooxin/next-chat:$VERSION
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
